version: '3.7'
services:
    redis:
        image: redis
        restart: always    
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./postgres/:/docker-entrypoint-initdb.d/:ro
            - ./out:/out
    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./kaggle.json:/usr/local/airflow/.kaggle/kaggle.json:ro
            - ./requirements.txt:/requirements.txt:ro
            - ./dags:/usr/local/airflow/dags
            - ./out:/usr/local/airflow/out
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    superset:
        image: amancevice/superset
        restart: always
        depends_on:
        - postgres
        - redis
        ports:
        - "8088:8088"
        volumes:
        - ./superset/config.py:/etc/superset/superset_config.py            